import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubIJTheme;

import javax.swing.*;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 Este JDialog es utilizado para que el usuario introduzca la palabra por
 la que desee sustituir la que se marcó como incorrecta.
 */
public class ReplaceModal extends javax.swing.JDialog {
    
    private MainFrame parentFrame;

    public ReplaceModal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        /* obtenemos al padre del JDialog para utilizar sus métodos*/
        parentFrame = (MainFrame)this.getParent();
    }

    /**
     * Con este método actualizamos el JLabel que muestra la palabra
     * que se desee reemplazar.
     * */
    public void updateLabelContent(){
        textLabel.setText(parentFrame.getMissingWord());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wordInput = new javax.swing.JTextField();
        replaceButton = new javax.swing.JButton();
        textLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        wordInput.setFont(new java.awt.Font("Mulish", 0, 14)); // NOI18N

        replaceButton.setBackground(Color.decode("#106BC4"));
        replaceButton.setForeground(new java.awt.Color(255, 255, 255));
        replaceButton.setText("Reemplazar");
        replaceButton.setBorderPainted(false);
        replaceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        replaceButton.setFocusPainted(false);
        replaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceButtonActionPerformed(evt);
            }
        });

        textLabel.setFont(new java.awt.Font("Mulish", 1, 14)); // NOI18N
        textLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cancelButton.setBackground(Color.decode("#106BC4"));
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");
        cancelButton.setBorderPainted(false);
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.setFocusPainted(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wordInput)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(replaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(textLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este evento reemplaza la palabra seleccionada en el texto.
     * */
    private void replaceButtonActionPerformed(java.awt.event.ActionEvent evt) {
        parentFrame.replaceWord(wordInput.getText());
        wordInput.setText("");
        this.dispose();
    }

    /**
     * Este evento cierra la ventana y cancela el proceso de reemplazo.
     * */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        parentFrame.cancelReplace();
        wordInput.setText("");
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatGitHubIJTheme());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ReplaceModal.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ReplaceModal dialog = new ReplaceModal(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    private javax.swing.JButton cancelButton;
    private javax.swing.JButton replaceButton;
    private javax.swing.JLabel textLabel;
    private javax.swing.JTextField wordInput;
}
